-- Conectar a la base de datos
CONNECT TO GESTION;

-- Insertar en la tabla MEDICOS evitando duplicados
MERGE INTO MEDICA.MEDICOS AS T
USING (VALUES ('12345678A', 98765, 'Dr. Juan Pérez', 'Cardiología', 600123456)) AS S(DNI, NUMLICENCIA, NOMBRE, ESPECIALIDAD, TELEFONO)
ON T.DNI = S.DNI AND T.NUMLICENCIA = S.NUMLICENCIA
WHEN NOT MATCHED THEN
    INSERT (DNI, NUMLICENCIA, NOMBRE, ESPECIALIDAD, TELEFONO)
    VALUES (S.DNI, S.NUMLICENCIA, S.NOMBRE, S.ESPECIALIDAD, S.TELEFONO);

MERGE INTO MEDICA.MEDICOS AS T
USING (VALUES ('87654321B', 12366, 'Dr. Ana Gómez', 'Neurología', 611987654)) AS S(DNI, NUMLICENCIA, NOMBRE, ESPECIALIDAD, TELEFONO)
ON T.DNI = S.DNI AND T.NUMLICENCIA = S.NUMLICENCIA
WHEN NOT MATCHED THEN
    INSERT (DNI, NUMLICENCIA, NOMBRE, ESPECIALIDAD, TELEFONO)
    VALUES (S.DNI, S.NUMLICENCIA, S.NOMBRE, S.ESPECIALIDAD, S.TELEFONO);

-- Insertar en la tabla PACIENTES evitando duplicados
MERGE INTO MEDICA.PACIENTES AS T
USING (VALUES ('11111111A', 1000001, 'Carlos López', 654123988)) AS S(DNI, NSS, NOMBRE, TELEFONO)
ON T.DNI = S.DNI AND T.NSS = S.NSS
WHEN NOT MATCHED THEN
    INSERT (DNI, NSS, NOMBRE, TELEFONO)
    VALUES (S.DNI, S.NSS, S.NOMBRE, S.TELEFONO);

MERGE INTO MEDICA.PACIENTES AS T
USING (VALUES ('22222222B', 1000002, 'María Fernández', 623987654)) AS S(DNI, NSS, NOMBRE, TELEFONO)
ON T.DNI = S.DNI AND T.NSS = S.NSS
WHEN NOT MATCHED THEN
    INSERT (DNI, NSS, NOMBRE, TELEFONO)
    VALUES (S.DNI, S.NSS, S.NOMBRE, S.TELEFONO);

MERGE INTO MEDICA.PACIENTES AS T
USING (VALUES ('33333333C', 1000003, 'Pedro Sánchez', 698741236)) AS S(DNI, NSS, NOMBRE, TELEFONO)
ON T.DNI = S.DNI AND T.NSS = S.NSS
WHEN NOT MATCHED THEN
    INSERT (DNI, NSS, NOMBRE, TELEFONO)
    VALUES (S.DNI, S.NSS, S.NOMBRE, S.TELEFONO);

MERGE INTO MEDICA.PACIENTES AS T
USING (VALUES ('44444444D', 1000004, 'Lucía Rodríguez', 677852963)) AS S(DNI, NSS, NOMBRE, TELEFONO)
ON T.DNI = S.DNI AND T.NSS = S.NSS
WHEN NOT MATCHED THEN
    INSERT (DNI, NSS, NOMBRE, TELEFONO)
    VALUES (S.DNI, S.NSS, S.NOMBRE, S.TELEFONO);

-- Insertar en la tabla PRUEBAS evitando duplicados
MERGE INTO MEDICA.PRUEBAS AS T
USING (VALUES ('11111111A', '12345678A', 'Electrocardiograma', DATE('2024-02-15'), 'Normal')) AS S(DNI_PACIENTE, DNI_MEDICO, TIPO_PRUEBA, FECHA, RESULTADO)
ON T.DNI_PACIENTE = S.DNI_PACIENTE AND T.DNI_MEDICO = S.DNI_MEDICO
WHEN NOT MATCHED THEN
    INSERT (DNI_PACIENTE, DNI_MEDICO, TIPO_PRUEBA, FECHA, RESULTADO)
    VALUES (S.DNI_PACIENTE, S.DNI_MEDICO, S.TIPO_PRUEBA, S.FECHA, S.RESULTADO);

MERGE INTO MEDICA.PRUEBAS AS T
USING (VALUES ('22222222B', '12345678A', 'Ecografía', DATE('2024-02-10'), 'Sin anomalías')) AS S(DNI_PACIENTE, DNI_MEDICO, TIPO_PRUEBA, FECHA, RESULTADO)
ON T.DNI_PACIENTE = S.DNI_PACIENTE AND T.DNI_MEDICO = S.DNI_MEDICO
WHEN NOT MATCHED THEN
    INSERT (DNI_PACIENTE, DNI_MEDICO, TIPO_PRUEBA, FECHA, RESULTADO)
    VALUES (S.DNI_PACIENTE, S.DNI_MEDICO, S.TIPO_PRUEBA, S.FECHA, S.RESULTADO);

MERGE INTO MEDICA.PRUEBAS AS T
USING (VALUES ('33333333C', '87654321B', 'Resonancia magnética', DATE('2024-02-18'), 'Lesión detectada en L3-L4')) AS S(DNI_PACIENTE, DNI_MEDICO, TIPO_PRUEBA, FECHA, RESULTADO)
ON T.DNI_PACIENTE = S.DNI_PACIENTE AND T.DNI_MEDICO = S.DNI_MEDICO
WHEN NOT MATCHED THEN
    INSERT (DNI_PACIENTE, DNI_MEDICO, TIPO_PRUEBA, FECHA, RESULTADO)
    VALUES (S.DNI_PACIENTE, S.DNI_MEDICO, S.TIPO_PRUEBA, S.FECHA, S.RESULTADO);

MERGE INTO MEDICA.PRUEBAS AS T
USING (VALUES ('44444444D', '87654321B', 'Análisis de sangre', DATE('2024-02-15'), 'Niveles normales')) AS S(DNI_PACIENTE, DNI_MEDICO, TIPO_PRUEBA, FECHA, RESULTADO)
ON T.DNI_PACIENTE = S.DNI_PACIENTE AND T.DNI_MEDICO = S.DNI_MEDICO
WHEN NOT MATCHED THEN
    INSERT (DNI_PACIENTE, DNI_MEDICO, TIPO_PRUEBA, FECHA, RESULTADO)
    VALUES (S.DNI_PACIENTE, S.DNI_MEDICO, S.TIPO_PRUEBA, S.FECHA, S.RESULTADO);

-- Desconectar de la base de datos
CONNECT RESET;

