--------------------
-- MOSTRAR DATOS INSERTADOS EN CADA TABLA
--------------------
SELECT * FROM oficina;
SELECT * FROM cliente;
SELECT * FROM cuenta;
SELECT * FROM cuentacorriente;
SELECT * FROM cuentaahorro;
SELECT * FROM operacion;
SELECT * FROM operacionefectiva;
SELECT * FROM transferencia;

SELECT cl.NOMBRE, cl.APELLIDOS, c.PREFIJOIBAN, c.NUMEROCUENTA, c.SALDO 
FROM CLIENTE cl, CUENTA c 
WHERE EXISTS (
    SELECT 1
    FROM TABLE(c.REF_TITULAR) t
    WHERE t.COLUMN_VALUE = REF(cl) 
);

INSERT INTO CLIENTE VALUES (
    CLIENTEUDT(
        '12345678X', 
        'Cliente Prueba', 
        'Apellido Prueba',
        TO_DATE('2000-01-01', 'YYYY-MM-DD'),
        '+34678901234',
        'Calle Falsa 123',
        'email@prueba.com'
    )
);

INSERT INTO CUENTA VALUES ( --> FALLO PORQUE NO SE PUEDE INSERTAR DIRECTAMENTE EN CUENTA
    CUENTAUDT(
        'ES99', 
        '00000000000000000000',
        SYSDATE - 10, 
        1000.00, 
        CLIENTE_REFS(
            (SELECT REF(c) FROM CLIENTE c WHERE c.DNI_VAL = '12345678X')
        )
    )
);

INSERT INTO OFICINA VALUES (
    OFICINAUDT(
        0048,  -- Código de 4 dígitos (48 se almacenará como 0048 por el trigger trg_codigo_oficina)
        'Dirección de la Oficina 0048',
        '+34 111 222 333'
    )
);

SELECT * FROM OFICINA WHERE CODIGOOFICINA = 0048;

ALTER TRIGGER trg_prevent_insert_cuenta DISABLE;

INSERT INTO CUENTACORRIENTE VALUES (
    CUENTACORRIENTEUDT(
        'ES56',
        '12345678901234567890',
        SYSDATE - 10,
        5000.00,
        CLIENTE_REFS((SELECT REF(c) FROM CLIENTE c WHERE c.DNI_VAL = '12345678X')),
        (SELECT REF(o) FROM OFICINA o WHERE o.CODIGOOFICINA = 0048)  -- Usar código válido
    )
);

ALTER TRIGGER trg_prevent_insert_cuenta ENABLE;

SELECT PREFIJOIBAN, NUMEROCUENTA 
FROM CUENTACORRIENTE 
WHERE PREFIJOIBAN = 'ES56'
  AND NUMEROCUENTA = '12345678901234567890';

SELECT PREFIJOIBAN, NUMEROCUENTA 
FROM CUENTA
WHERE PREFIJOIBAN = 'ES56'
  AND NUMEROCUENTA = '12345678901234567890';

ALTER TRIGGER trg_prevent_insert_operacion DISABLE;

INSERT INTO OPERACIONEFECTIVA VALUES (
    OPERACIONEFECTIVAUDT(
        1001,
        TO_TIMESTAMP('2025-12-12 14:30:00', 'YYYY-MM-DD HH24:MI:SS'),
        200.00,
        'Prueba operación futura',
        (SELECT REF(c) FROM CUENTA c WHERE c.PREFIJOIBAN = 'ES56' AND c.NUMEROCUENTA = '12345678901234567890'),
        'INGRESO',
        (SELECT REF(o) FROM OFICINA o WHERE o.CODIGOOFICINA = 0048)
    )
);

ALTER TRIGGER trg_prevent_insert_operacion ENABLE;

---------------------------------------------------------

-- Consulta de operaciones efectivas
SELECT 
    CODIGO,
    TO_CHAR(FECHAYHORA, 'YYYY-MM-DD HH24:MI:SS') AS FECHAYHORA,
    CUANTIA,
    DESCRIPCION,
    DEREF(REF_CUENTAEMISORA).PREFIJOIBAN AS PREFIJOIBAN_EMISOR,
    DEREF(REF_CUENTAEMISORA).NUMEROCUENTA AS NUMEROCUENTA_EMISOR,
    TIPOOPERACION,
    DEREF(REF_SUCURSAL).CODIGOOFICINA AS CODIGOOFICINA_SUCURSAL
FROM OPERACIONEFECTIVA;


-- Consulta de cuentas corrientes con detalles de la oficina
SELECT 
    cc.PREFIJOIBAN AS IBAN_PREFIJO,
    cc.NUMEROCUENTA AS NUMERO_CUENTA,
    cc.SALDO,
    DEREF(cc.REF_OFICINA).CODIGOOFICINA AS CODIGO_OFICINA,
    DEREF(cc.REF_OFICINA).DIRECCION AS DIRECCION_OFICINA,
    DEREF(cc.REF_OFICINA).TEL AS TELEFONO_OFICINA
FROM 
    CUENTACORRIENTE cc;


-- Consulta de operaciones efectivas con detalles de la cuenta emisora y la oficina
SELECT 
    oe.CODIGO AS CODIGO_OPERACION,
    oe.FECHAYHORA,
    oe.CUANTIA,
    oe.DESCRIPCION,
    oe.TIPOOPERACION,
    DEREF(oe.REF_CUENTAEMISORA).PREFIJOIBAN AS IBAN_EMISOR,
    DEREF(oe.REF_CUENTAEMISORA).NUMEROCUENTA AS NUMERO_CUENTA_EMISOR,
    DEREF(oe.REF_SUCURSAL).CODIGOOFICINA AS CODIGO_OFICINA,
    DEREF(oe.REF_SUCURSAL).DIRECCION AS DIRECCION_OFICINA
FROM 
    OPERACIONEFECTIVA oe;


-- Consulta de transferencias con detalles de las cuentas emisora y receptora
SELECT 
    t.CODIGO AS CODIGO_TRANSFERENCIA,
    t.FECHAYHORA,
    t.CUANTIA,
    t.DESCRIPCION,
    DEREF(t.REF_CUENTAEMISORA).PREFIJOIBAN AS IBAN_EMISOR,
    DEREF(t.REF_CUENTAEMISORA).NUMEROCUENTA AS NUMERO_CUENTA_EMISOR,
    DEREF(t.REF_CUENTARECEPTORA).PREFIJOIBAN AS IBAN_RECEPTOR,
    DEREF(t.REF_CUENTARECEPTORA).NUMEROCUENTA AS NUMERO_CUENTA_RECEPTOR
FROM 
    TRANSFERENCIA t;


-- Consulta de operaciones (efectivas y transferencias) realizadas por una cuenta específica
SELECT 
    'EFECTIVA' AS TIPO_OPERACION,
    oe.CODIGO AS CODIGO_OPERACION,
    oe.FECHAYHORA,
    oe.CUANTIA,
    oe.DESCRIPCION,
    oe.TIPOOPERACION
FROM 
    OPERACIONEFECTIVA oe
WHERE 
    DEREF(oe.REF_CUENTAEMISORA).PREFIJOIBAN = 'ES56'  
    AND DEREF(oe.REF_CUENTAEMISORA).NUMEROCUENTA = '12345678901234567890'
UNION ALL
SELECT 
    'TRANSFERENCIA' AS TIPO_OPERACION,
    t.CODIGO AS CODIGO_OPERACION,
    t.FECHAYHORA,
    t.CUANTIA,
    t.DESCRIPCION,
    NULL AS TIPOOPERACION
FROM 
    TRANSFERENCIA t
WHERE 
    DEREF(t.REF_CUENTAEMISORA).PREFIJOIBAN = 'ES56'  
    AND DEREF(t.REF_CUENTAEMISORA).NUMEROCUENTA = '12345678901234567890';

-- Consulta de cuentas de ahorro con interés y saldo
SELECT 
    ca.PREFIJOIBAN AS IBAN_PREFIJO,
    ca.NUMEROCUENTA AS NUMERO_CUENTA,
    ca.SALDO,
    ca.INTERES
FROM 
    CUENTAAHORRO ca;


-- Consulta de oficinas con el número de cuentas corrientes asociadas
SELECT 
    o.CODIGOOFICINA AS CODIGO_OFICINA,
    o.DIRECCION AS DIRECCION_OFICINA,
    COUNT(cc.PREFIJOIBAN) AS NUMERO_CUENTAS_CORRIENTES
FROM 
    OFICINA o
LEFT JOIN 
    CUENTACORRIENTE cc ON DEREF(cc.REF_OFICINA).CODIGOOFICINA = o.CODIGOOFICINA
GROUP BY 
    o.CODIGOOFICINA, o.DIRECCION;

-- Consulta de transferencias entre dos cuentas específicas
SELECT 
    t.CODIGO AS CODIGO_TRANSFERENCIA,
    t.FECHAYHORA,
    t.CUANTIA,
    t.DESCRIPCION,
    DEREF(t.REF_CUENTAEMISORA).PREFIJOIBAN AS IBAN_EMISOR,
    DEREF(t.REF_CUENTAEMISORA).NUMEROCUENTA AS NUMERO_CUENTA_EMISOR,
    DEREF(t.REF_CUENTARECEPTORA).PREFIJOIBAN AS IBAN_RECEPTOR,
    DEREF(t.REF_CUENTARECEPTORA).NUMEROCUENTA AS NUMERO_CUENTA_RECEPTOR
FROM 
    TRANSFERENCIA t
WHERE 
    (DEREF(t.REF_CUENTAEMISORA).PREFIJOIBAN = 'ES56'  
    AND DEREF(t.REF_CUENTAEMISORA).NUMEROCUENTA = '12345678901234567890')
    OR 
    (DEREF(t.REF_CUENTARECEPTORA).PREFIJOIBAN = 'ES56'  
    AND DEREF(t.REF_CUENTARECEPTORA).NUMEROCUENTA = '12345678901234567890');

    