BEGIN
  FOR obj IN (
    SELECT object_name, object_type
    FROM user_objects
    WHERE object_type = 'TYPE'
      AND object_name IN (
        'OPERACIONEFECTIVAUDT',
        'TRANSFERENCIAUDT',
        'OPERACIONUDT',
        'CUENTACORRIENTEUDT',
        'CUENTAAHORROUDT',
        'CUENTAUDT',
        'CLIENTEUDT',
        'OFICINAUDT',
        'IBAN',
        'TELEFONO',
        'DNI'
      )
  ) LOOP
    BEGIN
      EXECUTE IMMEDIATE 'DROP TYPE ' || obj.object_name || ' FORCE';
    EXCEPTION
      WHEN OTHERS THEN
        NULL;
    END;
  END LOOP;
END;
/

-- Tipos básicos
CREATE OR REPLACE TYPE DNI AS OBJECT (
  VALOR VARCHAR2(20)
) FINAL;
/

CREATE OR REPLACE TYPE TELEFONO AS OBJECT (
  VALOR VARCHAR2(50)
) FINAL;
/

CREATE OR REPLACE TYPE IBAN AS OBJECT (
  PREFIJOIBAN VARCHAR2(4),
  NUMEROCUENTA VARCHAR2(30)
) FINAL;
/

-- Tipos principales
CREATE OR REPLACE TYPE OFICINAUDT AS OBJECT (
  CODIGOOFICINA NUMBER(4),
  DIRECCION VARCHAR2(200),
  TEL TELEFONO
) INSTANTIABLE NOT FINAL;
/

CREATE OR REPLACE TYPE CLIENTEUDT AS OBJECT (
  DNI_VAL DNI,
  NOMBRE VARCHAR2(50),
  APELLIDOS VARCHAR2(75),
  FECHADENACIMIENTO DATE,
  TEL TELEFONO,
  DIRECCION VARCHAR2(200),
  EMAIL VARCHAR2(250)
) INSTANTIABLE NOT FINAL;
/

CREATE OR REPLACE TYPE CUENTAUDT AS OBJECT (
  CUENTA_IBAN IBAN,
  FECHACREACION DATE,
  SALDO NUMBER(15,2),
  REF_TITULAR REF CLIENTEUDT
) INSTANTIABLE NOT FINAL;
/

CREATE OR REPLACE TYPE CUENTACORRIENTEUDT UNDER CUENTAUDT (
  REF_OFICINA REF OFICINAUDT
) INSTANTIABLE NOT FINAL;
/

CREATE OR REPLACE TYPE CUENTAAHORROUDT UNDER CUENTAUDT (
  INTERES NUMBER(5,2)
) INSTANTIABLE NOT FINAL;
/ 

CREATE OR REPLACE TYPE OPERACIONUDT AS OBJECT (
  CODIGO NUMBER(10),
  FECHAYHORA TIMESTAMP,
  CUANTIA NUMBER(15,2),
  DESCRIPCION VARCHAR2(4000),
  REF_CUENTAEMISORA REF CUENTAUDT
) INSTANTIABLE NOT FINAL;
/

CREATE OR REPLACE TYPE OPERACIONEFECTIVAUDT UNDER OPERACIONUDT (
  TIPOOPERACION VARCHAR2(20),
  REF_SUCURSAL REF OFICINAUDT
) INSTANTIABLE NOT FINAL;
/

CREATE OR REPLACE TYPE TRANSFERENCIAUDT UNDER OPERACIONUDT (
  REF_CUENTARECEPTORA REF CUENTAUDT
) INSTANTIABLE NOT FINAL;
/
